"""Stage 6 — finalize each persona folder: write PROVENANCE.txt and return per-persona
stats for the run index. The persona artifacts (persona.json, MEMORY.md, asset_pack.json,
crosslinks.json, tasks.json, pii_index.json, workspace/, docs/) are already written in place
by earlier stages; this stamps provenance and counts what landed.
"""

from __future__ import annotations

import json
from pathlib import Path

from .. import SYNTHETIC_BANNER
from ..events import Event, EventBus, EventType

_PROVENANCE = (
    "{banner}\n\n"
    "Persona: {pid}\n"
    "Everything in this folder is synthetic test data generated by synthgen.\n"
    "It contains NO real personal information. Identifiers, documents, images, and audio\n"
    "are fabricated for privacy-research and agent-evaluation purposes only.\n"
)


def _count_assets(pdir: Path) -> int:
    n = 0
    for sub in ("docs",):
        d = pdir / sub
        if d.is_dir():
            n += sum(1 for _ in d.iterdir() if _.is_file())
    return n


def package_persona(run_dir: Path, persona: dict, tasks: list[dict], bus: EventBus) -> dict:
    pid = persona["persona_id"]
    pdir = run_dir / "personas" / pid
    pdir.mkdir(parents=True, exist_ok=True)
    (pdir / "PROVENANCE.txt").write_text(_PROVENANCE.format(banner=SYNTHETIC_BANNER, pid=pid), encoding="utf-8")

    face = run_dir / "assets" / "faces" / f"{pid}.png"
    stats = {
        "persona_id": pid,
        "name": persona.get("full_name", pid),
        "n_tasks": len(tasks),
        "n_assets": _count_assets(pdir) + (1 if face.exists() else 0),
        "has_face": face.exists(),
    }
    bus.emit(Event(EventType.PERSONA_PACKAGED, persona_id=pid, stage="package",
                   msg=f"{pid} packaged: {stats['n_tasks']} tasks, {stats['n_assets']} assets",
                   data=stats))
    return stats


def package_all(run_dir: Path, personas: list[dict], tasks_map: dict[str, list[dict]],
                bus: EventBus) -> list[dict]:
    return [package_persona(run_dir, p, tasks_map.get(p["persona_id"], []), bus) for p in personas]
