"""Single source of truth for which image kinds are genuine PHOTOGRAPHS (generated by the
Nanobanana diffusion model and thus paid) vs documents (rendered crisply via HTML, free).
Documents — including ID cards and the photorealistic `.real` composites — are offline/free;
only real photos + persona faces cost money.
"""

from __future__ import annotations

FACE_KINDS = {"avatar", "profile-photo", "face", "selfie"}

PHOTO_SCENE_KINDS = {
    "family-photo", "pet-photo", "photo-album", "travel-photo", "event-photo",
    "art-portfolio", "hobby-progress-photo", "doorbell-snapshot", "license-plate-photo",
}

PAID_IMAGE_KINDS = FACE_KINDS | PHOTO_SCENE_KINDS


def is_paid_image(kind: str) -> bool:
    return kind in PAID_IMAGE_KINDS
